import React from 'react';
import { GraduationCap, ShieldAlert, AlertCircle } from 'lucide-react';

interface EducationalDisclaimerProps {
  variant?: 'banner' | 'inline' | 'compact' | 'footer';
  className?: string;
  customText?: string;
  actionContext?: 'BUY_SELL_HOLD' | 'REBALANCE' | 'ARBITRAGE' | 'AI_SIGNAL' | 'GENERAL';
}

export const EducationalDisclaimer: React.FC<EducationalDisclaimerProps> = ({
  variant = 'banner',
  className = '',
  customText,
  actionContext = 'BUY_SELL_HOLD',
}) => {
  const getDefaultText = () => {
    switch (actionContext) {
      case 'REBALANCE':
        return 'All buy, sell, and hold rebalancing allocations generated by Agent 14 are strictly for educational and hypothetical research demonstration only. They do not constitute financial advice, investment advisory, or a solicitation under SEBI regulations.';
      case 'ARBITRAGE':
        return 'Dual-exchange price differentials and buy/sell execution suggestions are theoretical mathematical simulations for educational purposes only. Not financial advice.';
      case 'AI_SIGNAL':
        return 'Any algorithmic consensus ratings, target price thresholds, or buy/sell/hold evaluations generated by the AI assistant are strictly for educational use and research exploration.';
      case 'BUY_SELL_HOLD':
      default:
        return 'Educational-Use Disclaimer: All outputs, ratings, and signals indicating Buy, Sell, or Hold are strictly for simulated educational and analytical demonstration purposes only. They do not constitute financial advice or personalized investment recommendations. Consult a certified financial advisor before making actual financial decisions.';
    }
  };

  const displayText = customText || getDefaultText();

  if (variant === 'inline') {
    return (
      <div
        className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-amber-950/40 border border-amber-800/60 text-amber-300 text-[11px] font-mono ${className}`}
        title="Any Buy, Sell, or Hold signal is strictly for educational research demonstration."
      >
        <GraduationCap className="w-3.5 h-3.5 text-amber-400 shrink-0" />
        <span className="font-semibold uppercase tracking-wider text-[10px]">Educational Use Only:</span>
        <span className="truncate max-w-xs sm:max-w-md">{displayText}</span>
      </div>
    );
  }

  if (variant === 'compact') {
    return (
      <div
        className={`flex items-start gap-2 p-2.5 rounded-xl bg-slate-950/80 border border-amber-900/40 text-slate-300 text-[11px] font-mono ${className}`}
      >
        <GraduationCap className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
        <div className="flex-1">
          <span className="text-amber-400 font-bold uppercase tracking-wider text-[10px] mr-1.5">
            Educational Disclaimer:
          </span>
          <span>{displayText}</span>
        </div>
      </div>
    );
  }

  if (variant === 'footer') {
    return (
      <div
        className={`pt-2.5 border-t border-slate-800/80 text-[11px] text-slate-400 font-mono flex items-center justify-between gap-2 ${className}`}
      >
        <div className="flex items-center gap-1.5 text-amber-400/90 font-semibold">
          <GraduationCap className="w-3.5 h-3.5 shrink-0" />
          <span className="text-[10px] uppercase tracking-wider">Educational Use Only</span>
        </div>
        <span className="text-right text-[10px] text-slate-400 truncate max-w-sm sm:max-w-xl">
          Buy/Sell/Hold outputs are hypothetical simulated models; not investment advice.
        </span>
      </div>
    );
  }

  // Default: 'banner'
  return (
    <div
      className={`p-3.5 rounded-xl bg-gradient-to-r from-amber-950/50 via-slate-900 to-amber-950/30 border border-amber-700/50 shadow-sm ${className}`}
    >
      <div className="flex items-start gap-3">
        <div className="p-1.5 rounded-lg bg-amber-900/40 border border-amber-600/40 text-amber-400 shrink-0 mt-0.5">
          <GraduationCap className="w-4 h-4" />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <h5 className="text-xs font-bold text-amber-300 font-mono uppercase tracking-wider flex items-center gap-1.5">
              <span>Educational-Use Disclaimer</span>
            </h5>
            <span className="px-1.5 py-0.2 rounded bg-amber-900/60 text-amber-200 border border-amber-700/60 text-[9px] font-mono font-bold">
              NON-ADVISORY
            </span>
          </div>
          <p className="text-xs text-slate-300 font-mono mt-1 leading-relaxed">
            {displayText}
          </p>
        </div>
      </div>
    </div>
  );
};
